<a href="https://colab.research.google.com/github/abigasansuri-1806/MAJOR-PROJECT/blob/main/major_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import nltk
import re
df=pd.read_csv("/content/drive/MyDrive/SMART KNOWER/MAJOR/data.csv", engine='python')
df=df.dropna()
x=df.iloc[:,1].values
y=df.iloc[:,2].values

In [2]:
processed_tweets=[]
for i in x:
  #removing all special characters
  prc_tweet=re.sub(r'\W',' ',str(i))

  #removing all single characters
  prc_tweet=re.sub(r'\s+[a-zA-Z]\s+',' ',prc_tweet)

  #removing single characters from the start
  prc_tweet = re.sub(r'\^[a-zA-Z]\s+',' ', prc_tweet)

  # Substituting multiple spaces with single space
  prc_tweet= re.sub(r'\s+',' ', prc_tweet, flags=re.I)

  # Removing prefixed 'b'
  prc_tweet = re.sub(r'^b\s+','', prc_tweet)

  # Converting to Lowercase
  prc_tweet = prc_tweet.lower()

  processed_tweets.append(prc_tweet)
processed_tweets

['last session of the day http twitpic com 67ezh',
 ' shanghai is also really exciting precisely skyscrapers galore good tweeps in china sh bj ',
 'recession hit veronique branquinho she has to quit her company such shame ',
 ' happy bday ',
 ' http twitpic com 4w75p like it ',
 ' that great weee visitors ',
 'i think everyone hates me on here lol',
 ' soooooo wish could but im in school and myspace is completely blocked',
 ' and within short time of the last clue all of them',
 ' what did you get my day is alright haven done anything yet leaving soon to my stepsister though ',
 'my bike was put on hold should have known that argh total bummer',
 ' checked we didn win',
 ' and you re on twitter did the tavern bore you that much ',
 'i in va for the weekend my youngest son turns 2 tomorrow it makes me kinda sad he is getting so big check out my twipics',
 'its coming out the socket feel like my phones hole is not virgin that how loose it is ',
 'so hot today _ don like it and hate my ne

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [4]:
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english')) 
x= tfidfconverter.fit_transform(processed_tweets).toarray()
np.any(np.isnan(x))

False

In [5]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0,stratify=y)

In [6]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)  
text_classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [7]:
predictions = text_classifier.predict(x_test)

In [8]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
 
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  
print(accuracy_score(y_test, predictions))

[[107  77  16]
 [ 42 199  45]
 [ 11  67 143]]
              precision    recall  f1-score   support

    negative       0.67      0.54      0.59       200
     neutral       0.58      0.70      0.63       286
    positive       0.70      0.65      0.67       221

    accuracy                           0.64       707
   macro avg       0.65      0.63      0.63       707
weighted avg       0.64      0.64      0.63       707

0.635077793493635


In [9]:
txt="It is a beautiful life"
prc_tweet=re.sub(r'\W',' ',txt)

prc_tweet=re.sub(r'\s+[a-zA-Z]\s+',' ',prc_tweet)

prc_tweet = re.sub(r'\^[a-zA-Z]\s+','', prc_tweet)

prc_tweet= re.sub(r'\s+',' ', prc_tweet, flags=re.I)

prc_tweet = re.sub(r'^b\s+','', prc_tweet)

prc_tweet = prc_tweet.lower()

prc_tweet

'it is beautiful life'

In [10]:
tst=tfidfconverter.transform([prc_tweet]).toarray()
text_classifier.predict(tst)[0]

'neutral'

In [11]:
!pip install streamlit
!pip install pyngrok==4.1.1
from pyngrok import ngrok

     |████████████████████████████████| 7.5MB 5.9MB/s 
     |████████████████████████████████| 81kB 6.5MB/s 
     |████████████████████████████████| 4.6MB 43.9MB/s 
     |████████████████████████████████| 163kB 44.8MB/s 
     |████████████████████████████████| 112kB 39.0MB/s 
     |████████████████████████████████| 122kB 45.6MB/s 
     |████████████████████████████████| 71kB 6.2MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13448 sha256=4e05886dbb0286060915d8ddbb6e6646b54bd20001f3a59fc41a9233ac6d1f5f
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.0 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


  Created wheel for pyngrok: filename=pyngrok-4.1.1-cp37-none-any.whl size=15971 sha256=af7fe62f3f0250a1d7779c06bf276ef94c0af1e4cc8b2ea2cc5aaea2f9c80209
  Stored in directory: /root/.cache/pip/wheels/97/71/0d/1695f7c8815c0beb3b5d9b35d6eec9243c87e6070fbe3977fa
Successfully built pyngrok


In [12]:
import pickle
pickle.dump(text_classifier,open("TextClassifier","wb"))

In [13]:
%%writefile app.py
import streamlit as st
import pickle
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.corpus import stopwords
import pandas as pd

st.title("Sentiment Analysis")
df=pd.read_csv("/content/drive/MyDrive/SMART KNOWER/MAJOR/data.csv",encoding="ISO-8859-1")
df=df.dropna()
x=df.iloc[:,0].values
y=df.iloc[:,1].values
processed_tweets=[]
for i in x:
  prc_tweet=re.sub(r'\W',' ',str(i))
  prc_tweet=re.sub(r'\s+[a-zA-Z]\s+',' ',prc_tweet)
  prc_tweet = re.sub(r'\^[a-zA-Z]\s+',' ', prc_tweet)
  prc_tweet= re.sub(r'\s+',' ', prc_tweet, flags=re.I)
  prc_tweet = re.sub(r'^b\s+','', prc_tweet)
  prc_tweet = prc_tweet.lower()
  processed_tweets.append(prc_tweet)
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=3, max_df=0.7, stop_words=stopwords.words('english'))
tfidfconverter.fit_transform(processed_tweets).toarray()
text_classifier=pickle.load(open("TextClassifier","rb"))
select = st.text_input('Enter your message')
prc_tweet=re.sub(r'\W',' ',select)
prc_tweet=re.sub(r'\s+[a-zA-Z]\s+',' ',prc_tweet)
prc_tweet = re.sub(r'\^[a-zA-Z]\s+',' ', prc_tweet)
prc_tweet= re.sub(r'\s+',' ', prc_tweet, flags=re.I)
prc_tweet = re.sub(r'^b\s+','', prc_tweet)
prc_tweet = prc_tweet.lower()
tst=tfidfconverter.transform([prc_tweet]).toarray()
op=text_classifier.predict(tst)
st.title(op[0])

Writing app.py


In [14]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://82fb17d08b19.ngrok.io'